In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
distance_df = pd.read_csv('distance.csv')
pellet_df = pd.read_csv('pellet.csv')

In [35]:
distance_df.head()

,Day,Date,Time,201808 reversal1-25:Irrad,201808 reversal1-26:Sham,201808 reversal1-28:Irrad,201809 reversal-13:Sham,201809 reversal-14:Irrad,201809 reversal-15:Irrad,201809 reversal-16:Sham,...,201811 reversal1-18:Sham,201811 reversal1-20:Irrad,201811 reversal2-21:Irrad,201811 reversal2-22:Sham,201811 reversal2-23:Sham,201811 reversal2-24:Irrad,201812 reversal-1:Sham,201812 reversal-2:Irrad,201812 reversal-3:Sham,201812 reversal-4:Irrad
0,-5,5/27/50,17:12,NaN,NaN,NaN,203.462,165.051,0.0,160.431,...,112.264,0.0,0.0,183.325,101.892,233.284,131.395,208.479,141.803,231.773
1,-5,5/27/50,17:13,NaN,NaN,NaN,133.539,189.141,0.0,152.866,...,187.448,0.0,0.0,164.514,165.498,173.539,147.012,149.991,161.234,287.352
2,-5,5/27/50,17:14,NaN,NaN,NaN,13.632,202.818,0.0,10.340,...,95.392,0.0,0.0,130.638,45.457,182.345,121.037,216.182,128.220,222.124
3,-5,5/27/50,17:15,NaN,NaN,NaN,77.649,0.000,0.0,75.035,...,101.233,0.0,0.0,111.376,0.000,166.933,134.530,259.667,147.407,267.275
4,-5,5/27/50,17:16,NaN,NaN,NaN,219.045,0.000,0.0,18.502,...,0.000,0.0,0.0,72.598,0.000,250.807,214.366,135.046,158.703,178.139

In [36]:
pellet_df.head()

,Day,Date,Time,201808 reversal1-25:Irrad,201808 reversal1-26:Sham,201808 reversal1-28:Irrad,201809 reversal-13:Sham,201809 reversal-14:Irrad,201809 reversal-15:Irrad,201809 reversal-16:Sham,...,201811 reversal1-18:Sham,201811 reversal1-20:Irrad,201811 reversal2-21:Irrad,201811 reversal2-22:Sham,201811 reversal2-23:Sham,201811 reversal2-24:Irrad,201812 reversal-1:Sham,201812 reversal-2:Irrad,201812 reversal-3:Sham,201812 reversal-4:Irrad
0,-5,5/27/50,17:12,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-5,5/27/50,17:13,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-5,5/27/50,17:14,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-5,5/27/50,17:15,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-5,5/27/50,17:16,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
distance_df.shape

(19709, 24)

In [38]:
pellet_df.shape

(19709, 24)

In [65]:
distance_filt = distance_df.drop(['201808 reversal1-25:Irrad', '201808 reversal1-26:Sham', 
                                 '201808 reversal1-28:Irrad'], axis=1)
distance_filt.head()

,Day,Date,Time,201809 reversal-13:Sham,201809 reversal-14:Irrad,201809 reversal-15:Irrad,201809 reversal-16:Sham,201810 reversal-17:Sham,201810 reversal-18:Irrad,201810 reversal-20:Sham,...,201811 reversal1-18:Sham,201811 reversal1-20:Irrad,201811 reversal2-21:Irrad,201811 reversal2-22:Sham,201811 reversal2-23:Sham,201811 reversal2-24:Irrad,201812 reversal-1:Sham,201812 reversal-2:Irrad,201812 reversal-3:Sham,201812 reversal-4:Irrad
0,-5,5/27/50,17:12,203.462,165.051,0.0,160.431,22.830,64.380,357.014,...,112.264,0.0,0.0,183.325,101.892,233.284,131.395,208.479,141.803,231.773
1,-5,5/27/50,17:13,133.539,189.141,0.0,152.866,77.129,122.548,225.947,...,187.448,0.0,0.0,164.514,165.498,173.539,147.012,149.991,161.234,287.352
2,-5,5/27/50,17:14,13.632,202.818,0.0,10.340,32.856,121.389,182.863,...,95.392,0.0,0.0,130.638,45.457,182.345,121.037,216.182,128.220,222.124
3,-5,5/27/50,17:15,77.649,0.000,0.0,75.035,79.196,116.402,194.682,...,101.233,0.0,0.0,111.376,0.000,166.933,134.530,259.667,147.407,267.275
4,-5,5/27/50,17:16,219.045,0.000,0.0,18.502,97.081,181.265,286.284,...,0.000,0.0,0.0,72.598,0.000,250.807,214.366,135.046,158.703,178.139

In [46]:
pellet_filt.shape

(19709, 18)

In [54]:
distance_filt.shape

(19709, 18)

# Filter Pellet Data

In [67]:
pellet_filt = pellet_df.drop(['201808 reversal1-25:Irrad', '201808 reversal1-26:Sham', 
                                 '201808 reversal1-28:Irrad'], axis=1)
pellet_filt.head()

,Day,Date,Time,201809 reversal-13:Sham,201809 reversal-14:Irrad,201809 reversal-15:Irrad,201809 reversal-16:Sham,201810 reversal-17:Sham,201810 reversal-18:Irrad,201810 reversal-20:Sham,...,201811 reversal1-18:Sham,201811 reversal1-20:Irrad,201811 reversal2-21:Irrad,201811 reversal2-22:Sham,201811 reversal2-23:Sham,201811 reversal2-24:Irrad,201812 reversal-1:Sham,201812 reversal-2:Irrad,201812 reversal-3:Sham,201812 reversal-4:Irrad
0,-5,5/27/50,17:12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-5,5/27/50,17:13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-5,5/27/50,17:14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-5,5/27/50,17:15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-5,5/27/50,17:16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
pellet_day = pellet_filt.groupby('Day').agg(sum)[pellet_day[0]]
pellet_day

,201809 reversal-13:Sham,201809 reversal-14:Irrad,201809 reversal-15:Irrad,201809 reversal-16:Sham,201810 reversal-17:Sham,201810 reversal-18:Irrad,201810 reversal-20:Sham,201811 reversal1-17:Irrad,201811 reversal1-18:Sham,201811 reversal1-20:Irrad,201811 reversal2-21:Irrad,201811 reversal2-22:Sham,201811 reversal2-23:Sham,201811 reversal2-24:Irrad,201812 reversal-1:Sham,201812 reversal-2:Irrad,201812 reversal-3:Sham,201812 reversal-4:Irrad
Day,,,,,,,,,,,,,,,,,,
-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-2,142.0,184.0,127.0,148.0,179.0,134.0,113.0,179.0,155.0,142.0,150.0,157.0,118.0,182.0,163.0,172.0,153.0,180.0
-1,211.0,216.0,130.0,182.0,177.0,157.0,166.0,195.0,187.0,215.0,183.0,187.0,123.0,182.0,166.0,194.0,160.0,181.0
0,25.0,15.0,15.0,18.0,7.0,8.0,6.0,7.0,15.0,14.0,17.0,12.0,15.0,35.0,17.0,14.0,6.0,6.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,110.0,44.0,39.0,162.0,133.0,25.0,173.0,62.0,113.0,48.0,55.0,149.0,109.0,30.0,130.0,40.0,117.0,55.0
4,139.0,74.0,36.0,169.0,168.0,25.0,165.0,203.0,150.0,74.0,64.0,180.0,145.0,38.0,152.0,51.0,155.0,204.0
5,155.0,111.0,37.0,183.0,180.0,91.0,162.0,37.0,142.0,108.0,21.0,162.0,131.0,32.0,156.0,12.0,107.0,103.0
6,219.0,184.0,111.0,185.0,181.0,149.0,188.0,145.0,175.0,182.0,119.0,183.0,137.0,174.0,172.0,108.0,128.0,50.0
7,213.0,219.0,118.0,186.0,171.0,131.0,167.0,184.0,177.0,198.0,164.0,179.0,147.0,171.0,157.0,201.0,138.0,165.0
8,204.0,210.0,106.0,168.0,158.0,135.0,187.0,182.0,167.0,188.0,184.0,162.0,147.0,165.0,155.0,192.0,137.0,219.0
9,0.0,7.0,3.0,12.0,1.0,3.0,6.0,1.0,5.0,22.0,10.0,10.0,10.0,5.0,8.0,7.0,8.0,0.0

In [82]:
pellet_day[0]

KeyError: 0